import{a as f,i,S as u}from"./assets/vendor-BxlLpZ63.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function e(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function d(r){try{return(await f.get("https://pixabay.com/api/",{params:{key:"56652561-3c3afa13e53c98b396d0dbe19",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(a){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(a)}}const p=new u(".gallery a",{captionsData:"alt",captionDelay:250});function m(r){r.innerHTML=""}function g(r){r.classList.add("is-active")}function y(r){r.classList.remove("is-active")}function h(r,a){const o=r.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info-container">
          <div class="info-block"><span class="info-title">Likes</span><span class="info-value">${e.likes}</span></div>
          <div class="info-block"><span class="info-title">Views</span><span class="info-value">${e.views}</span></div>
          <div class="info-block"><span class="info-title">Comments</span><span class="info-value">${e.comments}</span></div>
          <div class="info-block"><span class="info-title">Downloads</span><span class="info-value">${e.downloads}</span></div>
        </div>
      </li>`).join("");a.insertAdjacentHTML("beforeend",o),p.refresh()}const v=document.querySelector(".form"),l=document.querySelector(".gallery"),c=document.querySelector(".loader");v.addEventListener("submit",async r=>{r.preventDefault(),m(l);const o=new FormData(r.currentTarget).get("search-text").trim();if(r.currentTarget.reset(),o===""){i.warning({title:"Caution",message:"Search field cannot be empty!",position:"topRight"});return}g(c);try{const e=await d(o);if(!e.length){i.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e,l)}catch(e){console.log(e)}finally{y(c)}});
//# sourceMappingURL=index.js.map
